version: "3.7"

services:
  pg:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - NamedVolume:/var/lib/postgres/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - pg
    links:
      - pg
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./docker/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    links:
      - pg
    ports:
      - 8000:8080

volumes:
  NamedVolume:
