version: "3.7"

services:
  gitbucket:
    image: gitbucket/gitbucket
    restart: always
    ports:
      - 8080:8080 
      - 29418:29418 
    volumes:
      - GitBucketVolume:/gitbucket
    environment:
      GITBUCKET_MAXFILESIZE: 104857600

volumes:
  GitBucketVolume:

