version: "3.7"

services:
  jenkins:
    image: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - JenkinsVolume:/var/jenkins_home

volumes:
  JenkinsVolume:
