version: "3.7"

services:
  pg:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - PostgresVolume:/var/lib/postgres/data
      - ./init:/docker-entrypoint-initdb.d
    command: >
      postgres -c 
      log_destination=stderr -c 
      log_statement=all -c 
      log_connections=on -c 
      log_disconnections=on
    environment:
      TZ: "Asia/Tokyo" 
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    user: "${UID}:${GID}"
    depends_on:
      - pg
    links:
      - pg
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./docker/pgadmin4:/var/lib/pgadmin
    environment:
      TZ: "Asia/Tokyo" 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  PostgresVolume:
